# Source global definitions
[[ -f /etc/bashrc ]] && source /etc/bashrc

# Source from dotfiles
source ~/.dotfiles/bash/aliases.sh

# Source local aliases
[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases

