# Source global definitions
[[ -f /etc/bashrc ]] && source /etc/bashrc

# Source from dotfiles
source ~/.dotfiles/bash/aliases

[[ -f ~/.profile ]] && source ~/.profile

# Source local aliases
[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases

# Reset prompt
PROMPT_COMMAND=""
